# Generated by Django 3.2 on 2022-04-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tokens',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Token or Royalty', max_digits=10000000, null=True),
        ),
    ]
